version: "3.8"
services:
  app:
    init: true
    build: .
    command: sleep infinity
    volumes:
      - ..:/app:cached
      - dotconfig:/home/app/.config

  mongo:
    image: mongo

volumes:
  dotconfig:
